CREATE DATABASE EMPDETAILS;
CREATE TABLE EMPINFO(
EMPID INT  IDENTITY(100,1)PRIMARY KEY,
EMPNAME VARCHAR(200),
DESIGNATION VARCHAR(200)
);

INSERT INTO EMPINFO(EMPNAME,DESIGNATION) VALUES('SURESH', 'ADMIN'),
												('ARUN','JR ENG'),
												('RAJESH', 'INTERN'),
												('SAKTHI', 'SR ENG'),
												('RAMYA', 'MANAGER'),
												('SWETHA', 'JR ENG'),
												('ANITHA', 'SR ENG'),
												('BAVI','TEAM LEAD'),
												('CITHRA', 'INTERN');

SELECT * FROM EMPINFO;

ALTER TABLE EMPINFO
drop column doj;

--handiling null
ALTER TABLE EMPINFO
ADD DOJ DATE null;

--using defalt
ALTER TABLE EMPINFO
drop column doj;

alter table EMPINFO
ADD DOJ DATE default '2022-07-12';

--UPDATE

UPDATE EMPINFO
SET DOJ='2017-07-01'
WHERE DESIGNATION='MANAGER';

UPDATE EMPINFO
SET DOJ='2025-08-04'
WHERE DESIGNATION ='INTERN';

UPDATE EMPINFO
SET DOJ='2020-03-01'
WHERE DESIGNATION ='TEAM LEAD';

UPDATE EMPINFO
SET DOJ='2024-04-07'
WHERE DESIGNATION IN('JR ENG','SR ENG');

DELETE EMPINFO
WHERE DESIGNATION='ADMIN';

INSERT INTO  EMPINFO (EMPNAME,DESIGNATION,DOJ) VALUES ('SURESH', 'ADMIN','2022-02-01');

CREATE TABLE EMPSALARY(
	EMPID INT,
	SALARY INT,
		);

 ALTER TABLE  EMPSALARY
 ADD CONSTRAINT FK_ID FOREIGN KEY(EMPID) REFERENCES EMPINFO(EMPID); 

 INSERT INTO EMPSALARY VALUES(101,200000),
							 (102,100000),
							 (103,700000),
							 (104,2400000),
							 (105,200000),
							 (106,2400000),
							 (107,1300000),
							 (108,100000),
							 (109,1200000);
 
 ALTER TABLE EMPSALARY
 ADD TAX FLOAT;

 SELECT EMPID,SALARY,SALARY*0.18 AS TAX FROM EMPSALARY;