DROP TABLE IF EXISTS EMPDETAILS ;
CREATE DATABASE EMPINFOMATION;
CREATE TABLE EMPDETASILS(
EMPID INT  IDENTITY(100,1)PRIMARY KEY,
EMPNAME VARCHAR(200),
DESIGNATION VARCHAR(200)
)


INSERT INTO EMPDETASILS(EMPNAME,DESIGNATION) VALUES('SURESH', 'ADMIN'),
												('ARUN','JR ENG'),
												('RAJESH', 'INTERN'),
												('SAKTHI', 'SR ENG'),
												('RAMYA', 'MANAGER'),
												('SWETHA', 'JR ENG'),
												('ANITHA', 'SR ENG'),
												('BAVI','TEAM LEAD'),
												('CITHRA', 'INTERN');

	CREATE TABLE EMPINCOME(
	EMPID INT,
	SALARY INT,
	CONSTRAINT FK_EMPIDS FOREIGN KEY(EMPID) REFERENCES EMPDETASILS(EMPID)
	);
	 INSERT INTO EMPINCOME VALUES(101,200000),
							 (102,100000),
							 (103,700000);
	 INSERT INTO EMPINCOME VALUES(104,200000),
							 (105,3500000),
							 (106,700000);
   INSERT INTO EMPINCOME VALUES(107,120000),
							 (108,100000);
	SELECT * FROM EMPINCOME;

--APPLY AGGREGATE FUN ON NUMERIC COLUMNS
SELECT COUNT(*) AS NO_OF_EMP FROM EMPDETASILS;
SELECT SUM(SALARY)AS TOTALCTC FROM EMPINCOME;
SELECT MAX(SALARY) AS MAXSALARY FROM EMPINCOME;
SELECT MIN(SALARY) AS MINSALARY FROM EMPINCOME;

--APPLY GROUPBY AND HAVING 
SELECT COUNT(*)FROM EMPDETASILS
GROUP BY DESIGNATION
HAVING COUNT(*) > 1;

--FIND SECOND HIGHEST SALARY
SELECT SALARY 
FROM EMPINCOME 
ORDER BY SALARY DESC 
OFFSET 1 ROWS 
FETCH NEXT 1 ROWS ONLY;